/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_carboncrystal_spine_SpineAnimation */

#ifndef _Included_com_carboncrystal_spine_SpineAnimation
#define _Included_com_carboncrystal_spine_SpineAnimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_carboncrystal_spine_SpineAnimation
 * Method:    step
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_carboncrystal_spine_SpineAnimation_step
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_carboncrystal_spine_SpineAnimation
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_carboncrystal_spine_SpineAnimation_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_carboncrystal_spine_SpineAnimation
 * Method:    setAnimation
 * Signature: (JILjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_carboncrystal_spine_SpineAnimation_setAnimation
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

/*
 * Class:     com_carboncrystal_spine_SpineAnimation
 * Method:    create
 * Signature: (Lcom/carboncrystal/spine/SpineAnimation;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_carboncrystal_spine_SpineAnimation_create
  (JNIEnv *, jobject, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
