/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_carboncrystal_spine_SpineContext */

#ifndef _Included_com_carboncrystal_spine_SpineContext
#define _Included_com_carboncrystal_spine_SpineContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_carboncrystal_spine_SpineContext
 * Method:    init
 * Signature: (Landroid/content/res/AssetManager;)J
 */
JNIEXPORT jlong JNICALL Java_com_carboncrystal_spine_SpineContext_init
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
